//
//  RequestStyleKit.h
//  Approve it!
//
//  Created by Udo Schneider on 25/01/15.
//  Copyright (c) 2015 Krodelin Software Solutions. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface RequestStyleKit : NSObject

// Drawing Methods
+ (void)drawGraph_textWithStatus: (NSString*)status;
+ (void)drawGraph_overlayWithStatus: (NSString*)status;

@end
